package cuentaBancaria;

import java.awt.Color;
import java.awt.Component;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InterfazLogin
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabelImagen.setIcon(elegirImagenTitulo());
        elegirImagenTitulo();
        
        
        
    }
    
    private String usuario = "";
    private String contraseña = "";
    private int contador = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGeneral = new javax.swing.JPanel();
        jPanelInicioSesion = new javax.swing.JPanel();
        jLabelSalir = new javax.swing.JLabel();
        jTextFieldTextoUsuario = new javax.swing.JTextField();
        jTextFieldBienvenida = new javax.swing.JTextField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldContraseña = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jPanelImagen = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelGeneral.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelGeneral.setOpaque(false);
        jPanelGeneral.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanelGeneralKeyPressed(evt);
            }
        });
        jPanelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInicioSesion.setBackground(new java.awt.Color(153, 153, 153));
        jPanelInicioSesion.setOpaque(false);
        jPanelInicioSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanelInicioSesionKeyPressed(evt);
            }
        });
        jPanelInicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarNF.png"))); // NOI18N
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSalirMousePressed(evt);
            }
        });
        jPanelInicioSesion.add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTextFieldTextoUsuario.setBackground(new java.awt.Color(0, 153, 0,0));
        jTextFieldTextoUsuario.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextFieldTextoUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldTextoUsuario.setText("Introduce tu nombre de usuario");
        jTextFieldTextoUsuario.setToolTipText("");
        jTextFieldTextoUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 0, 102)));
        jTextFieldTextoUsuario.setSelectionColor(new java.awt.Color(0, 204, 51));
        jTextFieldTextoUsuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldTextoUsuarioCaretUpdate(evt);
            }
        });
        jTextFieldTextoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTextoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTextoUsuarioFocusLost(evt);
            }
        });
        jTextFieldTextoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTextoUsuarioActionPerformed(evt);
            }
        });
        jTextFieldTextoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTextoUsuarioKeyPressed(evt);
            }
        });
        jPanelInicioSesion.add(jTextFieldTextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 500, 42));

        jTextFieldBienvenida.setEditable(false);
        jTextFieldBienvenida.setBackground(new java.awt.Color(0, 153, 0,0));
        jTextFieldBienvenida.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jTextFieldBienvenida.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldBienvenida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBienvenida.setText("BIENVENID@");
        jTextFieldBienvenida.setBorder(null);
        jTextFieldBienvenida.setFocusable(false);
        jPanelInicioSesion.add(jTextFieldBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 283, 42));

        jTextFieldUsuario.setEditable(false);
        jTextFieldUsuario.setBackground(new java.awt.Color(0, 153, 0,0));
        jTextFieldUsuario.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jTextFieldUsuario.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldUsuario.setText("Usuario:");
        jTextFieldUsuario.setToolTipText("");
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.setFocusable(false);
        jPanelInicioSesion.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 191, 42));

        jTextFieldContraseña.setEditable(false);
        jTextFieldContraseña.setBackground(new java.awt.Color(0, 153, 0,0));
        jTextFieldContraseña.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jTextFieldContraseña.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldContraseña.setText("Contraseña:");
        jTextFieldContraseña.setToolTipText("");
        jTextFieldContraseña.setBorder(null);
        jTextFieldContraseña.setFocusable(false);
        jTextFieldContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContraseñaActionPerformed(evt);
            }
        });
        jPanelInicioSesion.add(jTextFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 191, 42));

        jButtonAceptar.setBackground(new java.awt.Color(0, 204, 51));
        jButtonAceptar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setBorder(null);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanelInicioSesion.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 50));

        jPasswordFieldContraseña.setBackground(new java.awt.Color(0, 153, 0,0));
        jPasswordFieldContraseña.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jPasswordFieldContraseña.setForeground(new java.awt.Color(255, 255, 204));
        jPasswordFieldContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(102, 0, 102)));
        jPasswordFieldContraseña.setCaretColor(new java.awt.Color(102, 0, 102));
        jPasswordFieldContraseña.setEchoChar('*');
        jPasswordFieldContraseña.setSelectionColor(new java.awt.Color(0, 204, 51));
        jPasswordFieldContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldContraseñaFocusLost(evt);
            }
        });
        jPasswordFieldContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldContraseñaKeyPressed(evt);
            }
        });
        jPanelInicioSesion.add(jPasswordFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 500, 50));

        jPanelGeneral.add(jPanelInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 580, 390));

        jPanelImagen.setBackground(new java.awt.Color(0, 153, 0));
        jPanelImagen.setOpaque(false);
        jPanelImagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/city_building_128_old.png"))); // NOI18N
        jLabelImagen.setFocusable(false);
        jPanelImagen.add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 140, 150));

        jTextFieldTitulo.setEditable(false);
        jTextFieldTitulo.setBackground(new java.awt.Color(0, 153, 0,0));
        jTextFieldTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTextFieldTitulo.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldTitulo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTitulo.setText("ACCESO CUENTA");
        jTextFieldTitulo.setBorder(null);
        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        jPanelImagen.add(jTextFieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 50));

        jPanelGeneral.add(jPanelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 0, 260, 390));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        jPanelGeneral.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTextoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTextoUsuarioActionPerformed

    private void jTextFieldContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContraseñaActionPerformed

    private void jTextFieldTextoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTextoUsuarioFocusGained
        // TODO add your handling code here:
      
        if(jTextFieldTextoUsuario.getText().equals("Introduce tu nombre de usuario") & jTextFieldTextoUsuario.getForeground().equals(new Color(204,204,204))){
            jTextFieldTextoUsuario.setText("");
            jTextFieldTextoUsuario.setForeground(new Color(255,255,204));
        }
    }//GEN-LAST:event_jTextFieldTextoUsuarioFocusGained

    private void jTextFieldTextoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTextoUsuarioFocusLost
        // TODO add your handling code here:
        if(jTextFieldTextoUsuario.getText().equals("")){
            jTextFieldTextoUsuario.setText("Introduce tu nombre de usuario");
            jTextFieldTextoUsuario.setForeground(new Color(204,204,204));
        } 
    }//GEN-LAST:event_jTextFieldTextoUsuarioFocusLost

    private void jPasswordFieldContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusLost
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusLost

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        ProbarAceptar();
            
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jPasswordFieldContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPasswordFieldContraseñaFocusGained

    private void jPanelInicioSesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelInicioSesionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            ProbarAceptar();
        }
       
    }//GEN-LAST:event_jPanelInicioSesionKeyPressed

    private void jPanelGeneralKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelGeneralKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            
            ProbarAceptar();
        }
        
    }//GEN-LAST:event_jPanelGeneralKeyPressed

    private void jLabelSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelSalirMousePressed

    private void jLabelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseEntered
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("/img/cerrarSF.png"));
        jLabelSalir.setIcon(i);
    }//GEN-LAST:event_jLabelSalirMouseEntered

    private void jPasswordFieldContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseñaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            ProbarAceptar();
        }
    }//GEN-LAST:event_jPasswordFieldContraseñaKeyPressed

    private void jTextFieldTextoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTextoUsuarioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            ProbarAceptar();
        }
    }//GEN-LAST:event_jTextFieldTextoUsuarioKeyPressed

    private void jLabelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseExited
        // TODO add your handling code here:
        //ImageIcon i = new ImageIcon("./src/img/cerrarNF.png");
        ImageIcon i = new ImageIcon(getClass().getResource("/img/cerrarNF.png"));
        jLabelSalir.setIcon(i);
    }//GEN-LAST:event_jLabelSalirMouseExited

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldTextoUsuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldTextoUsuarioCaretUpdate
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextFieldTextoUsuarioCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
        
    }
    private void ProbarAceptar(){
    this.contraseña = jPasswordFieldContraseña.getText();
    this.usuario = this.usuario = jTextFieldTextoUsuario.getText();
    
    if(this.contraseña.equals("1234") & this.usuario.equals("alumno")){
                MenuCuenta it = new MenuCuenta();
                it.setVisible(true);
                this.dispose();
        } else{
            
            if(this.contador == 2){
                
                JOptionPane.showMessageDialog(null, "Demasiados intentos fallidos,Contacte con el administrador", "Error", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
                
            } else{
                
                JOptionPane.showMessageDialog(null, "Error al iniciar sesion. Prueba otra vez", "Error", JOptionPane.ERROR_MESSAGE);
                jPasswordFieldContraseña.setText("");
                jTextFieldTextoUsuario.setText("Introduce tu nombre de usuario");
                jTextFieldTextoUsuario.setForeground(new Color(204,204,204));
                this.contador++;
            }
            }
}
    private ImageIcon elegirImagenTitulo(){
        ImageIcon i = new ImageIcon("./src/img/city_building_128_old.png");
        int numIcon = (int)((Math.random()*(5-0))+0); //de 0 a 4.9999... pero al hacer (int) le quita la parte decimal asi q el max es 4
        
        if(numIcon == 0){
            i = new ImageIcon(getClass().getResource("/img/city_building_128_normal.png"));
        } else if(numIcon == 1){
            i = new ImageIcon(getClass().getResource("/img/city_building_128_green.png"));
        } else if(numIcon == 2){
            i = new ImageIcon(getClass().getResource("/img/city_building_128_orange.png"));
        } else if(numIcon == 3){
            i = new ImageIcon(getClass().getResource("/img/city_building_128_pink.png"));
        } else if(numIcon == 4){
            i = new ImageIcon(getClass().getResource("/img/city_building_128_purple.png"));
        }
        return i;
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JPanel jPanelInicioSesion;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldBienvenida;
    private javax.swing.JTextField jTextFieldContraseña;
    private javax.swing.JTextField jTextFieldTextoUsuario;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}

