/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuentaBancaria;

import javax.swing.ImageIcon;

/**
 *
 * @author tarde
 */
public class MenuCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCuenta.class.getName());

    /**
     * Creates new form MenuCuenta
     */
    public MenuCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelSalir = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelTfno = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelMvo = new javax.swing.JLabel();
        jLabelCliente1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabelCliente = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabelSaldo = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabelCuenta = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabelCantidad = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelDNI1 = new javax.swing.JLabel();
        jLabelDireccion1 = new javax.swing.JLabel();
        jLabelTfno1 = new javax.swing.JLabel();
        jLabelMvo1 = new javax.swing.JLabel();
        jLabelCantidad2 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCita = new javax.swing.JTable();
        jLabelCantidad3 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarNF.png"))); // NOI18N
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSalirMousePressed(evt);
            }
        });
        jPanelFondo.add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabelIcono.setBackground(new java.awt.Color(153, 153, 153));
        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono.png"))); // NOI18N
        jLabelIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelFondo.add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabelDireccion.setBackground(new java.awt.Color(153, 153, 153));
        jLabelDireccion.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(255, 255, 204));
        jLabelDireccion.setText("Direccion:");
        jLabelDireccion.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 120, -1));

        jLabelDNI.setBackground(new java.awt.Color(153, 153, 153));
        jLabelDNI.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelDNI.setForeground(new java.awt.Color(255, 255, 204));
        jLabelDNI.setText("DNI:");
        jLabelDNI.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 120, -1));

        jLabelTfno.setBackground(new java.awt.Color(153, 153, 153));
        jLabelTfno.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelTfno.setForeground(new java.awt.Color(255, 255, 204));
        jLabelTfno.setText("Tfno:");
        jLabelTfno.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelTfno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 120, -1));

        jLabelTipo.setBackground(new java.awt.Color(153, 153, 153));
        jLabelTipo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(255, 255, 204));
        jLabelTipo.setText("Tipo:");
        jPanelFondo.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 120, -1));

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 204));
        jTextField1.setBorder(null);
        jTextField1.setOpaque(true);
        jPanelFondo.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, 150, 30));

        jTextField3.setBackground(new java.awt.Color(153, 153, 153));
        jTextField3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 204));
        jTextField3.setBorder(null);
        jTextField3.setOpaque(true);
        jPanelFondo.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 290, 30));

        jTextField4.setBackground(new java.awt.Color(153, 153, 153));
        jTextField4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 204));
        jTextField4.setBorder(null);
        jTextField4.setOpaque(true);
        jPanelFondo.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 290, 30));

        jLabelNombre.setBackground(new java.awt.Color(153, 153, 153));
        jLabelNombre.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 204));
        jLabelNombre.setText("Nombre:");
        jLabelNombre.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 120, -1));

        jLabelMvo.setBackground(new java.awt.Color(153, 153, 153));
        jLabelMvo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelMvo.setForeground(new java.awt.Color(255, 255, 204));
        jLabelMvo.setText("Tipo Mvo:");
        jLabelMvo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelMvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 120, -1));

        jLabelCliente1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCliente1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCliente1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCliente1.setText("Cliente:");
        jLabelCliente1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, -1));

        jComboBox1.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanelFondo.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 150, -1));

        jComboBox2.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setBorder(null);
        jPanelFondo.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 250, -1));

        jComboBox3.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setBorder(null);
        jPanelFondo.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, 250, -1));

        jLabelCliente.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCliente.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCliente.setText("Cliente:");
        jPanelFondo.add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 120, -1));

        jTextField5.setBackground(new java.awt.Color(153, 153, 153));
        jTextField5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 204));
        jTextField5.setBorder(null);
        jTextField5.setOpaque(true);
        jPanelFondo.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 290, 30));

        jLabelSaldo.setBackground(new java.awt.Color(153, 153, 153));
        jLabelSaldo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelSaldo.setForeground(new java.awt.Color(255, 255, 204));
        jLabelSaldo.setText("Saldo:");
        jPanelFondo.add(jLabelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 710, 90, -1));

        jTextField6.setBackground(new java.awt.Color(153, 153, 153));
        jTextField6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 204));
        jTextField6.setBorder(null);
        jTextField6.setOpaque(true);
        jPanelFondo.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, 170, 30));

        jComboBox4.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setBorder(null);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanelFondo.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, 250, -1));

        jLabelCuenta.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCuenta.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCuenta.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCuenta.setText("Cuenta:");
        jLabelCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 120, -1));

        jComboBox5.setBackground(new java.awt.Color(153, 153, 153));
        jComboBox5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.setBorder(null);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanelFondo.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 160, -1));

        jLabelCantidad.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCantidad.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCantidad.setText("Cantidad:");
        jPanelFondo.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 120, -1));

        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        jTextField2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 204));
        jTextField2.setBorder(null);
        jTextField2.setOpaque(true);
        jPanelFondo.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 290, 30));

        jLabelNombre1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelNombre1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelNombre1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelNombre1.setText("Nombre:");
        jLabelNombre1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 120, -1));

        jLabelDNI1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelDNI1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelDNI1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelDNI1.setText("DNI:");
        jLabelDNI1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelDNI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 120, -1));

        jLabelDireccion1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelDireccion1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelDireccion1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelDireccion1.setText("Direccion:");
        jLabelDireccion1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 120, -1));

        jLabelTfno1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelTfno1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelTfno1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelTfno1.setText("Tfno:");
        jLabelTfno1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelTfno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 120, -1));

        jLabelMvo1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelMvo1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelMvo1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelMvo1.setText("Tipo Mvo:");
        jLabelMvo1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelMvo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 120, -1));

        jLabelCantidad2.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCantidad2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCantidad2.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCantidad2.setText("Cantidad:");
        jLabelCantidad2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 110, -1));

        jTextField7.setBackground(new java.awt.Color(153, 153, 153));
        jTextField7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 204));
        jTextField7.setBorder(null);
        jTextField7.setOpaque(true);
        jPanelFondo.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 710, 170, 30));

        jTextField8.setBackground(new java.awt.Color(153, 153, 153));
        jTextField8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 204));
        jTextField8.setBorder(null);
        jTextField8.setOpaque(true);
        jPanelFondo.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 170, 30));

        jTextField9.setBackground(new java.awt.Color(153, 153, 153));
        jTextField9.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 204));
        jTextField9.setBorder(null);
        jTextField9.setOpaque(true);
        jPanelFondo.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 170, 30));

        jTextField10.setBackground(new java.awt.Color(153, 153, 153));
        jTextField10.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 204));
        jTextField10.setBorder(null);
        jTextField10.setOpaque(true);
        jPanelFondo.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 170, 30));

        jTextField11.setBackground(new java.awt.Color(153, 153, 153));
        jTextField11.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 204));
        jTextField11.setBorder(null);
        jTextField11.setOpaque(true);
        jPanelFondo.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 170, 30));

        jTextField12.setBackground(new java.awt.Color(153, 153, 153));
        jTextField12.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 204));
        jTextField12.setBorder(null);
        jTextField12.setOpaque(true);
        jPanelFondo.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 170, 30));

        jScrollPane1.setForeground(new java.awt.Color(102, 0, 102));
        jScrollPane1.setOpaque(false);

        jTableCita.setBackground(new java.awt.Color(153, 153, 153));
        jTableCita.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableCita.setForeground(new java.awt.Color(0, 153, 0));
        jTableCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Tipo cita", "Tipo Mvto", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCita.setToolTipText("");
        jTableCita.setFocusTraversalPolicyProvider(true);
        jTableCita.setGridColor(new java.awt.Color(153, 153, 153));
        jTableCita.setSelectionBackground(new java.awt.Color(0, 204, 51));
        jTableCita.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTableCita);

        jPanelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 700, 310));

        jLabelCantidad3.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCantidad3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCantidad3.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCantidad3.setText("Cantidad:");
        jLabelCantidad3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 120, -1));

        jTextField13.setBackground(new java.awt.Color(153, 153, 153));
        jTextField13.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 204));
        jTextField13.setBorder(null);
        jTextField13.setOpaque(true);
        jPanelFondo.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 170, 30));

        jButtonAceptar.setBackground(new java.awt.Color(0, 204, 51));
        jButtonAceptar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setBorder(null);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 170, 120, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        jPanelFondo.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseEntered
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("/img/cerrarSF.png"));
        jLabelSalir.setIcon(i);
    }//GEN-LAST:event_jLabelSalirMouseEntered

    private void jLabelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseExited
        // TODO add your handling code here:
        //ImageIcon i = new ImageIcon("./src/img/cerrarNF.png");
        ImageIcon i = new ImageIcon(getClass().getResource("/img/cerrarNF.png"));
        jLabelSalir.setIcon(i);
    }//GEN-LAST:event_jLabelSalirMouseExited

    private void jLabelSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelSalirMousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuCuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCantidad2;
    private javax.swing.JLabel jLabelCantidad3;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCliente1;
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDNI1;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelDireccion1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelMvo;
    private javax.swing.JLabel jLabelMvo1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelTfno;
    private javax.swing.JLabel jLabelTfno1;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCita;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
