/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuentaBancaria;

import javax.swing.ImageIcon;

/**
 *
 * @author tarde
 */
public class MenuCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuCuenta.class.getName());

    /**
     * Creates new form MenuCuenta
     */
    public MenuCuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jLabelSalir = new javax.swing.JLabel();
        jLabelIcono = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelTfno = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldDir = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelMvo = new javax.swing.JLabel();
        jLabelCliente1 = new javax.swing.JLabel();
        jComboBoxMvo = new javax.swing.JComboBox<>();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabelCliente = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelSaldo = new javax.swing.JLabel();
        jTextFieldCantidad2 = new javax.swing.JTextField();
        jComboBoxCantidad = new javax.swing.JComboBox<>();
        jLabelCuenta = new javax.swing.JLabel();
        jComboBoxCuenta = new javax.swing.JComboBox<>();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldTfno = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelDNI1 = new javax.swing.JLabel();
        jLabelDireccion1 = new javax.swing.JLabel();
        jLabelTfno1 = new javax.swing.JLabel();
        jLabelMvo1 = new javax.swing.JLabel();
        jLabelCantidad2 = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();
        jTextFieldNombre2 = new javax.swing.JTextField();
        jTextFieldDNi2 = new javax.swing.JTextField();
        jTextFieldDir2 = new javax.swing.JTextField();
        jTextFieldTfno2 = new javax.swing.JTextField();
        jTextFieldMvo2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCita = new javax.swing.JTable();
        jLabelCantidad3 = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanelFondo.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarNF.png"))); // NOI18N
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelSalirMousePressed(evt);
            }
        });
        jPanelFondo.add(jLabelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabelIcono.setBackground(new java.awt.Color(153, 153, 153));
        jLabelIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono.png"))); // NOI18N
        jLabelIcono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelFondo.add(jLabelIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 200, 200));

        jLabelDireccion.setBackground(new java.awt.Color(153, 153, 153));
        jLabelDireccion.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelDireccion.setForeground(new java.awt.Color(255, 255, 204));
        jLabelDireccion.setText("Direccion:");
        jLabelDireccion.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 120, -1));

        jLabelDNI.setBackground(new java.awt.Color(153, 153, 153));
        jLabelDNI.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelDNI.setForeground(new java.awt.Color(255, 255, 204));
        jLabelDNI.setText("DNI:");
        jLabelDNI.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 120, -1));

        jLabelTfno.setBackground(new java.awt.Color(153, 153, 153));
        jLabelTfno.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelTfno.setForeground(new java.awt.Color(255, 255, 204));
        jLabelTfno.setText("Tfno:");
        jLabelTfno.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelTfno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 120, -1));

        jLabelTipo.setBackground(new java.awt.Color(153, 153, 153));
        jLabelTipo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(255, 255, 204));
        jLabelTipo.setText("Tipo:");
        jPanelFondo.add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 120, -1));

        jTextFieldCantidad.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCantidad.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldCantidad.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldCantidad.setBorder(null);
        jTextFieldCantidad.setOpaque(true);
        jPanelFondo.add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, 150, 30));

        jTextFieldDNI.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldDNI.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldDNI.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldDNI.setBorder(null);
        jTextFieldDNI.setOpaque(true);
        jPanelFondo.add(jTextFieldDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 290, 30));

        jTextFieldDir.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldDir.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldDir.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldDir.setBorder(null);
        jTextFieldDir.setOpaque(true);
        jPanelFondo.add(jTextFieldDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 290, 30));

        jLabelNombre.setBackground(new java.awt.Color(153, 153, 153));
        jLabelNombre.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 204));
        jLabelNombre.setText("Nombre:");
        jLabelNombre.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 120, -1));

        jLabelMvo.setBackground(new java.awt.Color(153, 153, 153));
        jLabelMvo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelMvo.setForeground(new java.awt.Color(255, 255, 204));
        jLabelMvo.setText("Tipo Mvo:");
        jLabelMvo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelMvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 120, -1));

        jLabelCliente1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCliente1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCliente1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCliente1.setText("Cliente:");
        jLabelCliente1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 100, -1));

        jComboBoxMvo.setBackground(new java.awt.Color(153, 153, 153));
        jComboBoxMvo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBoxMvo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMvo.setBorder(null);
        jComboBoxMvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMvoActionPerformed(evt);
            }
        });
        jPanelFondo.add(jComboBoxMvo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 150, -1));

        jComboBoxCliente.setBackground(new java.awt.Color(153, 153, 153));
        jComboBoxCliente.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCliente.setBorder(null);
        jPanelFondo.add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 30, 250, -1));

        jComboBoxTipo.setBackground(new java.awt.Color(153, 153, 153));
        jComboBoxTipo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxTipo.setBorder(null);
        jPanelFondo.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 70, 250, -1));

        jLabelCliente.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCliente.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCliente.setText("Cliente:");
        jPanelFondo.add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 120, -1));

        jTextFieldNombre.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldNombre.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.setOpaque(true);
        jPanelFondo.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 290, 30));

        jLabelSaldo.setBackground(new java.awt.Color(153, 153, 153));
        jLabelSaldo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelSaldo.setForeground(new java.awt.Color(255, 255, 204));
        jLabelSaldo.setText("Saldo:");
        jPanelFondo.add(jLabelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 710, 90, -1));

        jTextFieldCantidad2.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCantidad2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldCantidad2.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldCantidad2.setBorder(null);
        jTextFieldCantidad2.setOpaque(true);
        jPanelFondo.add(jTextFieldCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 640, 170, 30));

        jComboBoxCantidad.setBackground(new java.awt.Color(153, 153, 153));
        jComboBoxCantidad.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBoxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCantidad.setBorder(null);
        jComboBoxCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCantidadActionPerformed(evt);
            }
        });
        jPanelFondo.add(jComboBoxCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, 250, -1));

        jLabelCuenta.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCuenta.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCuenta.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCuenta.setText("Cuenta:");
        jLabelCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 120, -1));

        jComboBoxCuenta.setBackground(new java.awt.Color(153, 153, 153));
        jComboBoxCuenta.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBoxCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCuenta.setBorder(null);
        jComboBoxCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCuentaActionPerformed(evt);
            }
        });
        jPanelFondo.add(jComboBoxCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 160, -1));

        jLabelCantidad.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCantidad.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCantidad.setText("Cantidad:");
        jPanelFondo.add(jLabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, 120, -1));

        jTextFieldTfno.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldTfno.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldTfno.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldTfno.setBorder(null);
        jTextFieldTfno.setOpaque(true);
        jPanelFondo.add(jTextFieldTfno, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 290, 30));

        jLabelNombre1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelNombre1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelNombre1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelNombre1.setText("Nombre:");
        jLabelNombre1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 120, -1));

        jLabelDNI1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelDNI1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelDNI1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelDNI1.setText("DNI:");
        jLabelDNI1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelDNI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 120, -1));

        jLabelDireccion1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelDireccion1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelDireccion1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelDireccion1.setText("Direccion:");
        jLabelDireccion1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelDireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 120, -1));

        jLabelTfno1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelTfno1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelTfno1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelTfno1.setText("Tfno:");
        jLabelTfno1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelTfno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 120, -1));

        jLabelMvo1.setBackground(new java.awt.Color(153, 153, 153));
        jLabelMvo1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelMvo1.setForeground(new java.awt.Color(255, 255, 204));
        jLabelMvo1.setText("Tipo Mvo:");
        jLabelMvo1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelMvo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, 120, -1));

        jLabelCantidad2.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCantidad2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCantidad2.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCantidad2.setText("Cantidad:");
        jLabelCantidad2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 110, -1));

        jTextFieldSaldo.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldSaldo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldSaldo.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldSaldo.setBorder(null);
        jTextFieldSaldo.setOpaque(true);
        jPanelFondo.add(jTextFieldSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 710, 170, 30));

        jTextFieldNombre2.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldNombre2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldNombre2.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldNombre2.setBorder(null);
        jTextFieldNombre2.setOpaque(true);
        jPanelFondo.add(jTextFieldNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 170, 30));

        jTextFieldDNi2.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldDNi2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldDNi2.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldDNi2.setBorder(null);
        jTextFieldDNi2.setOpaque(true);
        jPanelFondo.add(jTextFieldDNi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 170, 30));

        jTextFieldDir2.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldDir2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldDir2.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldDir2.setBorder(null);
        jTextFieldDir2.setOpaque(true);
        jPanelFondo.add(jTextFieldDir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 170, 30));

        jTextFieldTfno2.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldTfno2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldTfno2.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldTfno2.setBorder(null);
        jTextFieldTfno2.setOpaque(true);
        jPanelFondo.add(jTextFieldTfno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 170, 30));

        jTextFieldMvo2.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldMvo2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldMvo2.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldMvo2.setBorder(null);
        jTextFieldMvo2.setOpaque(true);
        jPanelFondo.add(jTextFieldMvo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 170, 30));

        jScrollPane1.setForeground(new java.awt.Color(102, 0, 102));
        jScrollPane1.setOpaque(false);

        jTableCita.setBackground(new java.awt.Color(153, 153, 153));
        jTableCita.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTableCita.setForeground(new java.awt.Color(0, 153, 0));
        jTableCita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente", "Tipo cita", "Tipo Mvto", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCita.setToolTipText("");
        jTableCita.setFocusTraversalPolicyProvider(true);
        jTableCita.setGridColor(new java.awt.Color(153, 153, 153));
        jTableCita.setSelectionBackground(new java.awt.Color(0, 204, 51));
        jTableCita.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTableCita);

        jPanelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 700, 310));

        jLabelCantidad3.setBackground(new java.awt.Color(153, 153, 153));
        jLabelCantidad3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabelCantidad3.setForeground(new java.awt.Color(255, 255, 204));
        jLabelCantidad3.setText("Cantidad:");
        jLabelCantidad3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanelFondo.add(jLabelCantidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 120, -1));

        jTextFieldCliente.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldCliente.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jTextFieldCliente.setForeground(new java.awt.Color(255, 255, 204));
        jTextFieldCliente.setBorder(null);
        jTextFieldCliente.setOpaque(true);
        jPanelFondo.add(jTextFieldCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 170, 30));

        jButtonAceptar.setBackground(new java.awt.Color(0, 204, 51));
        jButtonAceptar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setBorder(null);
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 170, 120, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        jPanelFondo.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 850));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 1297, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseEntered
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("/img/cerrarSF.png"));
        jLabelSalir.setIcon(i);
    }//GEN-LAST:event_jLabelSalirMouseEntered

    private void jLabelSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseExited
        // TODO add your handling code here:
        //ImageIcon i = new ImageIcon("./src/img/cerrarNF.png");
        ImageIcon i = new ImageIcon(getClass().getResource("/img/cerrarNF.png"));
        jLabelSalir.setIcon(i);
    }//GEN-LAST:event_jLabelSalirMouseExited

    private void jLabelSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelSalirMousePressed

    private void jComboBoxMvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMvoActionPerformed

    private void jComboBoxCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCantidadActionPerformed

    private void jComboBoxCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCuentaActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuCuenta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JComboBox<String> jComboBoxCantidad;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxCuenta;
    private javax.swing.JComboBox<String> jComboBoxMvo;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelCantidad2;
    private javax.swing.JLabel jLabelCantidad3;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCliente1;
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDNI1;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelDireccion1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelIcono;
    private javax.swing.JLabel jLabelMvo;
    private javax.swing.JLabel jLabelMvo1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JLabel jLabelTfno;
    private javax.swing.JLabel jLabelTfno1;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCita;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCantidad2;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDNi2;
    private javax.swing.JTextField jTextFieldDir;
    private javax.swing.JTextField jTextFieldDir2;
    private javax.swing.JTextField jTextFieldMvo2;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre2;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextFieldTfno;
    private javax.swing.JTextField jTextFieldTfno2;
    // End of variables declaration//GEN-END:variables
}
